import type { Metadata } from 'next'
import localFont from 'next/font/local'

import './globals.css'

const pretend = localFont({
  src: '../public/fonts/PretendardVariable.woff2',
  variable: '--font-pretend',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode
}>) => {
  return (
    <html lang="en">
      <body className={`${pretend.variable}`}>{children}</body>
    </html>
  )
}

export default RootLayout
